version: "3"

services:
  db:
    container_name: db
    image: postgres:13.2-alpine
    env_file: ./config/.env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

networks:
  default:
    name: canintel-network
    external: True
